# Generated by Django 4.1.4 on 2023-01-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('3', 'Шопоголик'), ('2', 'Покупатель'), ('1', 'Новичок')], default='N', max_length=100),
        ),
    ]
