# Generated by Django 4.1.4 on 2023-01-25 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_profile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('Шопоголик', '3'), ('Покупатель', '2'), ('Новичок', '1')], default='Новичок', max_length=100),
        ),
    ]
