# Generated by Django 4.1.4 on 2023-01-25 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0003_alter_profile_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='scope_value',
            new_name='balance',
        ),
    ]
