# Generated by Django 4.1.4 on 2023-01-26 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0004_rename_scope_value_profile_balance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
    ]
