# Generated by Django 4.1.4 on 2023-01-26 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShopProduct',
            new_name='Category',
        ),
    ]
