# Generated by Django 4.1.4 on 2023-01-26 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0004_category_slug_product_slug_alter_category_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='shop',
            new_name='category',
        ),
    ]
