# Generated by Django 2.2 on 2022-12-06 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='create_date',
            field=models.DateField(verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.CharField(max_length=2000, verbose_name='Описание новости'),
        ),
        migrations.AlterField(
            model_name='news',
            name='edit_date',
            field=models.DateField(verbose_name='Дата редактирования'),
        ),
        migrations.AlterField(
            model_name='news',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Заголовок новости'),
        ),
    ]
