# Generated by Django 2.2 on 2022-12-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0002_auto_20221206_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_active',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.CharField(max_length=2000, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='user_name',
            field=models.CharField(max_length=100, verbose_name='Имя пользователя'),
        ),
    ]
