# Generated by Django 2.2 on 2022-12-07 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0003_auto_20221207_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsAndComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_news.Comments')),
                ('news', models.ManyToManyField(to='app_news.News')),
            ],
        ),
    ]
