# Generated by Django 2.2 on 2022-12-07 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0004_newsandcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='is_active',
            field=models.CharField(choices=[('A', 'Активно'), ('N', 'Неактивно')], default='N', max_length=100),
        ),
    ]
