# Generated by Django 2.2 on 2022-12-13 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0005_auto_20221207_1607'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsAndComment',
        ),
    ]
