# Generated by Django 2.2 on 2022-12-13 17:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0008_auto_20221213_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 13, 17, 59, 36, 702660), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='news',
            name='edit_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 13, 17, 59, 36, 702729), verbose_name='Дата редактирования'),
        ),
    ]
