# Generated by Django 2.2 on 2022-12-14 13:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0009_auto_20221213_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 14, 13, 32, 0, 223791), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='news',
            name='edit_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 14, 13, 32, 0, 223857), verbose_name='Дата редактирования'),
        ),
    ]
