# Generated by Django 2.2 on 2022-12-14 13:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0011_auto_20221214_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 14, 13, 48, 47, 746942), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='news',
            name='edit_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 14, 13, 48, 47, 746985), verbose_name='Дата редактирования'),
        ),
    ]
