# Generated by Django 2.2 on 2022-12-14 15:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0013_auto_20221214_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_user', to=settings.AUTH_USER_MODEL, verbose_name='Зареганый юзер'),
        ),
        migrations.AlterField(
            model_name='news',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 14, 15, 51, 29, 306050), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='news',
            name='edit_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 14, 15, 51, 29, 306149), verbose_name='Дата редактирования'),
        ),
    ]
