# Generated by Django 4.1.4 on 2022-12-20 15:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_news', '0015_auto_20221214_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Зареганый юзер'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='user_name',
            field=models.CharField(blank=True, default='Анонимный пользователь', max_length=100, verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='user_news',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app_news.news', verbose_name='связь коммента с новостью'),
        ),
        migrations.AlterField(
            model_name='news',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 20, 15, 40, 42, 323477), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='news',
            name='edit_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 20, 15, 40, 42, 323527), verbose_name='Дата редактирования'),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_active',
            field=models.CharField(choices=[('A', 'Одобрено'), ('N', 'Неактивно')], default='N', max_length=100),
        ),
        migrations.AddField(
            model_name='news',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app_news.category'),
        ),
    ]
