# Generated by Django 4.1.4 on 2022-12-20 18:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0017_alter_category_options_rename_tag_news_cat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app_news.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='news',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 20, 18, 52, 1, 490624), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='news',
            name='edit_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 20, 18, 52, 1, 490667), verbose_name='Дата редактирования'),
        ),
    ]
