# Generated by Django 2.2 on 2022-12-14 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_employment', '0002_resume'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resume',
            options={'permissions': (('can_publish', 'может публиковать'),), 'verbose_name': 'резюме', 'verbose_name_plural': 'резюме'},
        ),
    ]
